source 'https://rubygems.org'

gem 'sinatra'
gem 'sinatra-contrib'
gem 'mysql2'
gem 'mysql2-cs-bind'
gem 'erubis'
gem 'unicorn'

gem 'rack-mini-profiler'
gem 'rack-lineprof', git: 'https://github.com/kainosnoema/rack-lineprof'
gem 'pry-byebug'
gem 'pry-doc'
