version: '3.0'
services:
  app:
    image: showwin/ishocon2_app:latest
    command: /docker/start_app.sh
    volumes:
      - storage_app:/var/lib/mysql
      - storage_bundle:/var/lib/gems
      - ./:/home/ishocon/webapp
      - ./config/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./config/mysql/my.cnf:/etc/mysql/my.cnf
      - ./logs/nginx:/var/log/nginx
    ports:
      - 443:443
    working_dir: /home/ishocon/webapp/ruby
    depends_on:
      - redis
    environment:
      ISHOCON2_REDIS_HOST: redis
  storage_app:
    image: busybox
    volumes:
      - /var/lib/mysql
  redis:
    image: redis:4.0-alpine
    ports:
      - 6379:6379
  bench:
    image: showwin/ishocon2_bench:latest
    command: /docker/start_bench.sh
    volumes:
      - storage_bench:/var/lib/mysql
    links:
      - app

  storage_bench:
    image: busybox
    volumes:
      - /var/lib/mysql
  alp:
    image: saboyutaka/alp
    volumes:
      - ./logs/nginx:/logs
volumes:
  storage_bench:
  storage_app:
  storage_bundle:
