version: '3.0'
services:
  app:
    image: showwin/ishocon2_app:latest
    command: /docker/start_app.sh
    volumes:
      - storage_app:/var/lib/mysql
      - ./:/home/ishocon/webapp
      - ./config/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./config/mysql/my.cnf:/etc/mysql/my.cnf
      - ./logs/nginx:/var/log/nginx
    ports:
      - 443:443
    working_dir: /home/ishocon/webapp/ruby

  storage_app:
    image: busybox
    volumes:
      - /var/lib/mysql

  bench:
    image: showwin/ishocon2_bench:latest
    command: /docker/start_bench.sh
    volumes:
      - storage_bench:/var/lib/mysql
    links:
      - app

  storage_bench:
    image: busybox
    volumes:
      - /var/lib/mysql
  alp:
    image: saboyutaka/alp
    volumes:
      - ./logs/nginx:/logs
volumes:
  storage_bench:
  storage_app:
